DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

#APPS=ping6

HAVE_BANKING=1
UIP_CONF_IPV6=1
UIP_CONF_RPL=1

#PROJECT_SOURCEFILES += 

CONTIKI_PROJECT = udp-server6 tcp-server6 web-server6 

all: $(CONTIKI_PROJECT) 



CONTIKI = ../../..

include $(CONTIKI)/Makefile.include
